/**
 * Tests for staticComponentise.
 *
 * Ground truth from compaction-single-passthrough.json:
 *   [13] post-compaction-1.jsonl (1 msg)  → exact component list, timeline shape
 *   [20] segment-1.jsonl        (338 msgs) → exact component list, timeline values
 *
 * Note: Part IDs are generated by a global counter that differs between
 * test runs and recorded sessions, so we assert on values not IDs.
 */
import { describe, it, expect } from "vitest";
import { staticComponentise } from "../../operations/static-components";
import { addTokenCounts } from "../../operations/token-counting";
import { loadParsedArtifact } from "../helpers";

describe("staticComponentise", () => {
  it("matches recording [13]: post-compaction-1 components and structure", async () => {
    const { conversation } = loadParsedArtifact("post-compaction-1.jsonl");
    const counted = await addTokenCounts(conversation);
    const result = staticComponentise(counted);

    // Recording [13]: components
    expect(result.components).toEqual(["user.text"]);

    // Single message → single mapping entry → "user.text"
    expect(Object.keys(result.mapping).length).toBe(1);
    expect(Object.values(result.mapping)).toEqual(["user.text"]);

    // Recording [13]: timeline with exact token count
    expect(result.timeline.length).toBe(1);
    expect(result.timeline[0]).toEqual({
      messageIndex: 0,
      componentTokens: { "user.text": 2718 },
      totalTokens: 2718,
    });
  });

  it("matches recording [20]: segment-1 components, part count, timeline", async () => {
    const { conversation } = loadParsedArtifact("segment-1.jsonl");
    const counted = await addTokenCounts(conversation);
    const result = staticComponentise(counted);

    // Recording [20]: exact component list in order
    expect(result.components).toEqual([
      "user.image",
      "user.text",
      "assistant.reasoning",
      "assistant.text",
      "assistant.tool-call",
      "tool.tool-result",
    ]);

    // Recording [20]: mapping has 459 entries (100 shown + "359 more keys")
    const totalParts = counted.messages.reduce((s, m) => s + m.parts.length, 0);
    expect(Object.keys(result.mapping).length).toBe(totalParts);
    expect(totalParts).toBe(459);

    // Every mapping value must be one of the components
    for (const comp of Object.values(result.mapping)) {
      expect(result.components).toContain(comp);
    }

    // Recording [20]: 338 messages → 338 timeline entries
    expect(result.timeline.length).toBe(338);

    // Recording [20] timeline[0]: exact token match
    expect(result.timeline[0]!.componentTokens).toEqual({ "user.text": 50 });
    expect(result.timeline[0]!.totalTokens).toBe(50);

    // Recording [20] timeline[49]: exact token match
    expect(result.timeline[49]!.componentTokens).toEqual({
      "user.text": 482,
      "assistant.reasoning": 320,
      "assistant.text": 293,
      "assistant.tool-call": 2667,
      "tool.tool-result": 53332,
    });
    expect(result.timeline[49]!.totalTokens).toBe(57094);

    // Timeline is monotonically non-decreasing in totalTokens
    for (let i = 1; i < result.timeline.length; i++) {
      expect(result.timeline[i]!.totalTokens).toBeGreaterThanOrEqual(
        result.timeline[i - 1]!.totalTokens,
      );
    }
  });
});
